name: Playground Tests (Parallel Run)
on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Enter Email ID'
        required: true
      password:
        description: 'Enter Password'
        required: true
      browser:
        description: 'Select browser'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
          - Google Chrome
          - Microsoft Edge
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Create .env file from workflow inputs
        run: |
          echo email=${{ github.event.inputs.email }} >> .env
          echo password=${{ github.event.inputs.password }} >> .env
      - name: Run Playwright tests
        continue-on-error: true
        run: |
          npx playwright test wishlist.test.ts e2e.test.ts playground.test.ts --project="${{ github.event.inputs.browser }}"
      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev
      - name: Combine Best Allure Report to Single HTML
        run: |
          filename=$(basename "${{ github.event.inputs.testFile }}" .test.ts)
          node ./node_modules/allure-single-html-file-js/combine.js testArtifacts/allure-reports/allure-report-${filename}
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: testArtifacts/allure-reports
      - name: Upload Excel report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: excel-report
          path: testArtifacts/excel-reports
      - name: Upload CSV report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: csv-report
          path: testArtifacts/csv-reports