name: Playground Tests
on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Enter Email ID'
        required: true
      password:
        description: 'Enter Password'
        required: true
      testFile:
        description: 'Select test file to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - tests/playground.test.ts
          - tests/cart.test.ts
          - tests/e2e.test.ts
          - tests/wishlist.test.ts
      browser:
        description: 'Select browser'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
          - Google Chrome
          - Microsoft Edge
      parallelCount:
        description: 'How many times to run the same test file in parallel'
        required: true
        default: '1'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: ${{ fromJson(format('[{0}]', join(',', range(1, fromJson(inputs.parallelCount) + 1)))) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Create .env file from workflow inputs
        run: |
          echo email=${{ github.event.inputs.email }} >> .env
          echo password=${{ github.event.inputs.password }} >> .env
      - name: Run Playwright tests (instance ${{ matrix.instance }})
        run: |
          if [ "${{ github.event.inputs.testFile }}" = "all" ]; then
            npx playwright test --project="${{ github.event.inputs.browser }}" --reporter=html --output=playwright-report-${{ matrix.instance }}
          else
            npx playwright test "${{ github.event.inputs.testFile }}" --project="${{ github.event.inputs.browser }}" --reporter=html --output=playwright-report-${{ matrix.instance }}
          fi
      - name: Upload HTML Report ${{ matrix.instance }}
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.instance }}
          path: playwright-report-${{ matrix.instance }}
          retention-days: 30