name: Playground Tests (Parallel-Repeated)
on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Enter Email ID'
        required: true
      password:
        description: 'Enter Password'
        required: true
      testFile:
        description: 'Select test file to run'
        required: true
        default: 'all'
        type: choice
        options:
          - tests/playground.test.ts
          - tests/cart.test.ts
          - tests/e2e.test.ts
          - tests/wishlist.test.ts
      browser:
        description: 'Select browser'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
          - Google Chrome
          - Microsoft Edge
      parallelCount:
        description: 'How many times to run the same test file in parallel'
        required: true
        default: '1'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Create .env file from workflow inputs
        run: |
          echo email=${{ github.event.inputs.email }} >> .env
          echo password=${{ github.event.inputs.password }} >> .env
      - name: Run Playwright tests
        continue-on-error: true
        run: npx playwright test ${{ github.event.inputs.testFile }} --config=playwright-repeated-allure.config.ts --repeat-each=${{ github.event.inputs.parallelCount }} --workers=${{ github.event.inputs.parallelCount }} --project=${{ github.event.inputs.browser }}
      - name: Upload Best Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Best allure-report
          path: testArtifacts